"""empty message

Revision ID: 14b1d978d8e6
Revises: 
Create Date: 2020-11-14 07:42:29.540050

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '14b1d978d8e6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('paths',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('login', sa.String(length=256), nullable=True),
    sa.Column('hash_password', sa.String(length=1024), nullable=True),
    sa.Column('role', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('login')
    )
    op.create_table('tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users_paths',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('paths_id', sa.Integer(), nullable=True),
    sa.Column('ready', sa.Boolean(), nullable=False),
    sa.Column('coordinate', sa.String(length=128), nullable=False),
    sa.ForeignKeyConstraint(['paths_id'], ['paths.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users_paths')
    op.drop_table('tokens')
    op.drop_table('users')
    op.drop_table('paths')
    # ### end Alembic commands ###
